<?xml version="1.0"?>
<robot name="fixed_camera" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="camera_size" value="0.05" />
  <xacro:macro name="fixed_camera" params="number parent transX transY transZ">
    <link name="camera_${number}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${camera_size} ${camera_size} ${camera_size}" />
        </geometry>
        <material name="Green" />
      </visual>
    </link>


    <joint name="camera_${number}_joint" type="fixed">
      <origin xyz="${transX} ${transY} ${transZ}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="camera_${number}"/>
    </joint>

    <gazebo reference="camera_${number}">
      <material>Gazebo/Green</material>
      <visualize>true</visualize>
      <turnGravityOff>true</turnGravityOff>

      <sensor type="camera" name="camera_${number}_camera">
        <update_rate>10.0</update_rate>
        <camera name="camera_${number}_camera">
          <pose>${camera_size/2} 0 0 0 0 0}</pose>
          <horizontal_fov>1.3962634</horizontal_fov>
          <image>
            <width>800</width>
            <height>600</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>300</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>

        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>0.0</updateRate>
          <cameraName>camera_${number}_camera</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>camera_${number}</frameName>
          <hackBaseline>0.0</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>

    </gazebo>

  </xacro:macro>
</robot>
